OS := OS_LINUX
OS_CC           := gcc
OS_CCFLAGS      := -Wall -Wno-deprecated 
OS_CCDYNAFLAGS  := -fPIC
OS_CCDEBUGFLAGS := -g
OS_CPP          := $(OS_CC) -E
OS_LD           := gcc 
#OS_LDDYNAFLAGS  := -shared  -nostartfiles
LDFLAGS   = -shared 
OS_AR           := ar
OS_RM           := rm -f
OS_CP	        := cp
OS_LEX          := flex
OS_LEXFLAGS     :=
OS_YACC         := bison
OS_YACCFLAGS    := -b y -d -v
OS_LATEX        := latex
OS_DVI2PS       := dvips
OS_DVI2PDF      := dvipdfm
OS_METAPOST     := mpost
OS_LINUX        := OS_LINUX
